name: spatu
description: An Shoes Foccused E-Commerce App.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  another_flushbar: ^1.12.29
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.4.1
  equatable: ^2.0.5
  firebase_auth: ^4.2.7
  firebase_core: ^2.6.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_screenutil: ^5.6.1
  google_fonts: ^4.0.3
  http: ^0.13.5
  intl: ^0.17.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
